Repository huggingface/chat-ui, pull requests merged in 2023-10, with the labels that each got.

#469 Add manifest.json
  src/routes/+layout.svelte
  static/chatui/manifest.json
  static/huggingchat/manifest.json
Labels: enhancement, front

#472 Privacy update & readme linting
  PRIVACY.md
  README.md
Labels: enhancement

#470 Store preprompt in conversation (#422)
  src/lib/components/SystemPromptModal.svelte
  src/lib/components/chat/ChatMessages.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/types/Conversation.ts
  src/lib/types/SharedConversation.ts
  src/routes/+page.svelte
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.server.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/share/+server.ts
  src/routes/r/[id]/+page.server.ts
  src/routes/r/[id]/+page.svelte
Labels: enhancement, front, back

#478 Remove shared routes
  src/lib/shareConversation.ts
  src/lib/stores/pendingMessageIdToRetry.ts
  src/lib/utils/getShareUrl.ts
  src/routes/conversation/[id]/+page.server.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts
  src/routes/conversation/[id]/share/+server.ts
  src/routes/r/[id]/+page.server.ts
  src/routes/r/[id]/+page.svelte
  src/routes/r/[id]/+page.ts
  src/routes/r/[id]/message/[messageId]/prompt/+server.ts
Labels: enhancement, back

#479 Move some tasks to small model
  .env
  src/lib/server/generateFromDefaultEndpoint.ts
  src/lib/server/models.ts
  src/lib/server/summarize.ts
  src/routes/conversation/[id]/+page.svelte
Labels: enhancement, back

#488 Version upgrade to Svelte 4
  package-lock.json
  package.json
  src/lib/components/LoginModal.svelte
  src/lib/components/Modal.svelte
  src/lib/components/ModelCardMetadata.svelte
  src/lib/components/ModelsModal.svelte
  src/lib/components/ScrollToBottomBtn.svelte
  src/lib/components/SettingsModal.svelte
  src/lib/components/Switch.svelte
  src/lib/components/Toast.svelte
  src/lib/components/Tooltip.svelte
  src/lib/components/WebSearchToggle.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/routes/admin/export/+server.ts
Labels: back

#489 Add prompts templates to a markdown doc
  PROMPTS.md
  README.md
Labels: documentation

#499 Pass stop sequences properly to TGI
  src/lib/server/models.ts
Labels: bug, back

#493 Add a job in release action that updates the .env in prod
  .env.template
  .github/workflows/deploy-release.yml
  .gitignore
  update_env.py
Labels: back

#507 Feature customizable description
  .env
  .env.template
  README.md
  src/lib/components/chat/ChatIntroduction.svelte
Labels: enhancement, front

#503 Update websearch prompting & summary prompting
  .env.template
  src/lib/buildPrompt.ts
  src/lib/server/generateFromDefaultEndpoint.ts
  src/lib/server/models.ts
  src/lib/server/summarize.ts
  src/lib/server/websearch/generateQuery.ts
  src/lib/types/Template.ts
Labels: back, tools

#496 Feature/add OIDC optional tolerance and resource
  .env
  README.md
  src/lib/server/auth.ts
Labels: enhancement, back

#508 Update CI scripts for dotenv management
  .github/workflows/deploy-release.yml
  .gitignore
  package-lock.json
  package.json
  scripts/updateLocalEnv.ts
  scripts/updateProdEnv.ts
  update_env.py
Labels: back, spaces

#512 Title update occur when available
  src/lib/stores/titleUpdate.ts
  src/lib/types/MessageUpdate.ts
  src/routes/+layout.svelte
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/share/+server.ts
Labels: enhancement, front, back

#515 Switch chat model back to mistral, use zephyr for small tasks
  .env.template
  src/lib/server/models.ts
Labels: enhancement, back, models

#526 Bring back disclaimer modal & updates to guest mode
  .env.template
  src/lib/components/DisclaimerModal.svelte
  src/lib/components/LoginModal.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, front, back

#520 Add checkbox for displaying emojis in sidebar
  src/lib/components/SettingsModal.svelte
  src/lib/types/Settings.ts
  src/routes/+layout.server.ts
  src/routes/settings/+page.server.ts
Labels: enhancement, front, back

#536 Show model modal even if only one model is available
  src/lib/components/chat/ChatIntroduction.svelte
Labels: bug, front
