Repository huggingface/chat-ui, pull requests merged in 2023-11, with the labels that each got.

#541 Modular backends & support for openAI & AWS endpoints
  .env
  README.md
  package-lock.json
  package.json
  src/lib/server/endpoints/aws/endpointAws.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/endpoints/openai/endpointOai.ts
  src/lib/server/endpoints/openai/openAIChatToTextGenerationStream.ts
  src/lib/server/endpoints/openai/openAICompletionToTextGenerationStream.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/server/generateFromDefaultEndpoint.ts
  src/lib/server/modelEndpoint.ts
  src/lib/server/models.ts
  src/lib/server/summarize.ts
  src/lib/server/websearch/generateQuery.ts
  src/lib/utils/trimPrefix.ts
  src/lib/utils/trimSuffix.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, back

#552 Reset app title when clicking new chat
  src/routes/+page.svelte
Labels: bug, front

#531 Add support for tgi multimodal models
  .env.template
  PROMPTS.md
  README.md
  package-lock.json
  package.json
  src/lib/buildPrompt.ts
  src/lib/components/UploadBtn.svelte
  src/lib/components/chat/ChatInput.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/chat/FileDropzone.svelte
  src/lib/server/database.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/server/files/downloadFile.ts
  src/lib/server/files/uploadFile.ts
  src/lib/server/models.ts
  src/lib/stores/pendingMessage.ts
  src/lib/types/Message.ts
  src/lib/types/MessageUpdate.ts
  src/lib/types/Model.ts
  src/lib/utils/file2base64.ts
  src/lib/utils/models.ts
  src/routes/+layout.server.ts
  src/routes/+page.svelte
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/output/[sha256]/+server.ts
  src/routes/conversation/[id]/share/+server.ts
Labels: enhancement, front, back, models

#564 Update Node.js version to 20 in CI
  .github/workflows/deploy-release.yml
  .github/workflows/lint-and-test.yml
Labels: CI/CD

#563 Option for running websearch locally
  .env
  src/lib/server/websearch/runWebSearch.ts
  src/lib/server/websearch/searchWeb.ts
  src/lib/server/websearch/searchWebLocal.ts
Labels: enhancement, back, websearch

#557 Add a CI check for dockerfile build
  .github/workflows/lint-and-test.yml
  .gitignore
  conf/.env.ci
Labels: enhancement, CI/CD

#569 Add ollama endpoint support
  README.md
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/endpoints/ollama/endpointOllama.ts
  src/lib/server/models.ts
Labels: enhancement, back, models

#573 Add openchat to huggingchat config
  .env.template
  PROMPTS.md
Labels: enhancement, models

#561 [#547] fix stream generation bug
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: back

#578 fix: new chat when old one is still streaming
  src/lib/components/NavMenu.svelte
  src/lib/stores/isAborted.ts
  src/routes/conversation/[id]/+page.svelte
Labels: bug, front

#575 Make chat title summarization non blocking
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, back

#580 Open in new tab if cookies are disabled
  src/lib/components/DisclaimerModal.svelte
  src/lib/utils/cookiesAreEnabled.ts
Labels: bug, front
