Repository huggingface/chat-ui, pull requests merged in 2023-08, with the labels that each got.

#381 Add a login button
  src/lib/components/NavMenu.svelte
  src/routes/+layout.svelte
Labels: front

#401 Add Sagemaker support
  README.md
  package-lock.json
  package.json
  src/lib/server/generateFromDefaultEndpoint.ts
  src/lib/server/modelEndpoint.ts
  src/lib/server/models.ts
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, back

#400 Make all prompt templates configurable
  README.md
  package-lock.json
  package.json
  src/lib/buildPrompt.ts
  src/lib/server/models.ts
  src/lib/server/websearch/generateQuery.ts
  src/lib/server/websearch/summarizeWeb.ts
  src/lib/types/Template.ts
  src/lib/utils/template.ts
  src/routes/conversation/[id]/web-search/+server.ts
Labels: enhancement, back

#399 Support custom system prompts from the user
  src/lib/buildPrompt.ts
  src/lib/components/ModelsModal.svelte
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/server/models.ts
  src/lib/types/Model.ts
  src/lib/types/Settings.ts
  src/lib/types/Template.ts
  src/routes/+layout.server.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/+page.server.ts
Labels: enhancement, front, back

#410 Fix auth on websearch
  src/lib/buildPrompt.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts
  src/routes/conversation/[id]/summarize/+server.ts
  src/routes/r/[id]/message/[messageId]/prompt/+server.ts
Labels: bug, back
