Repository huggingface/chat-ui, pull requests merged in 2023-12, with the labels that each got.

#606 Only refresh cookie on POST
  src/hooks.server.ts
Labels: bug, back

#603 Session management improvements: Multi sessions, renew on login/logout
  src/hooks.server.ts
  src/lib/server/auth.ts
  src/lib/server/database.ts
  src/lib/types/MessageEvent.ts
  src/lib/types/Session.ts
  src/lib/types/User.ts
  src/routes/login/callback/+page.server.ts
  src/routes/login/callback/updateUser.spec.ts
  src/routes/login/callback/updateUser.ts
  src/routes/logout/+page.server.ts
Labels: enhancement, back

#579 Add support for passing an API key or any other custom token in the authorization header
  README.md
  src/lib/server/endpoints/aws/endpointAws.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/endpoints/ollama/endpointOllama.ts
  src/lib/server/endpoints/openai/endpointOai.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
Labels: bug, back

#582 Group conversations by date + small nav fixes
  src/lib/components/MobileNav.svelte
  src/lib/components/NavConversationItem.svelte
  src/lib/components/NavMenu.svelte
  src/routes/+layout.server.ts
Labels: bug, enhancement, front

#607 Get rid of the unused websearch collection, and the unused endpoint
  src/lib/server/database.ts
  src/routes/search/[id]/+server.ts
Labels: back

#591 Reworked settings menu
  package-lock.json
  package.json
  src/lib/actions/clickOutside.ts
  src/lib/components/DisclaimerModal.svelte
  src/lib/components/LoginModal.svelte
  src/lib/components/ModelsModal.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/SettingsModal.svelte
  src/lib/components/Switch.svelte
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/stores/settings.ts
  src/lib/types/Settings.ts
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/+layout.svelte
  src/routes/settings/+page.server.ts
  src/routes/settings/+page.svelte
  src/routes/settings/+server.ts
  src/routes/settings/[...model]/+page.svelte
  src/routes/settings/[...model]/+page.ts
Labels: enhancement, front

#613 Add `chat-ui` and `chat-ui-db` docker images
  .dockerignore
  .env
  .env.ci
  .github/workflows/build-image.yml
  .github/workflows/lint-and-test.yml
  .gitignore
  Dockerfile.local
  README.md
  entrypoint.sh
Labels: enhancement, CI/CD

#619 Add mixtral to models list in huggingchat
  .env.template
  PROMPTS.md
Labels: enhancement, models

#625 Add option to unlist a model
  src/lib/server/models.ts
  src/lib/types/Model.ts
  src/routes/+layout.server.ts
  src/routes/conversation/+server.ts
  src/routes/settings/+layout.svelte
  src/routes/settings/[...model]/+page.ts
Labels: enhancement, back

#624 Conditionally show the data sharing toggle
  src/routes/settings/+page.svelte
Labels: bug, front

#643 Reduce mistral v0.2 temp
  .env.template
Labels: models

#651 Add allow & blocklist for websearch
  .env
  src/lib/server/websearch/generateQuery.ts
Labels: enhancement, websearch

#652 Use a low temperature mistral for tasks
  .env.template
Labels: models

#653 Optimize dynamic import on vite startup
  vite.config.ts
Labels: dependencies

#663 Fix MODELS env
  README.md
Labels: bug, documentation

#664 Upgrade tailwindcss to version 3.4
  package-lock.json
  package.json
  src/lib/components/MobileNav.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/routes/+layout.svelte
Labels: dependencies

#665 add saslprep package for mongodb authentication
  package-lock.json
  package.json
Labels: dependencies

#659 Avoid duplicate MONGODB_URL in env local
  entrypoint.sh
Labels: enhancement, docker

#667 Use the new openchat model
  .env.template
Labels: models

#669 Add support for SerpStack API
  .env
  README.md
  src/lib/server/websearch/searchWeb.ts
  src/routes/+layout.server.ts
Labels: websearch

#672 Make mixtral the default model for new users
  .env.template
Labels: models

#645 Update share behaviour
  src/lib/components/chat/ChatWindow.svelte
  src/lib/shareConversation.ts
  src/lib/utils/share.ts
Labels: enhancement, front
