Repository huggingface/chat-ui, pull requests merged in 2023-07, with the labels that each got.

#319 Add support for HF summarization endpoint in the websearch
  src/lib/server/websearch/summarizeWeb.ts
Labels: enhancement, back

#350 Added Docker Space deployment docs
  README.md
Labels: documentation, enhancement

#342 Support rate limit based on user IP
  src/lib/types/MessageEvent.ts
  src/routes/conversation/[id]/+server.ts
Labels: back
