Repository huggingface/chat-ui, pull requests merged in 2024-06, with the labels that each got.

#1244 fix websearch on assistants
  src/lib/server/textGeneration/index.ts
Labels: bug, back, websearch, assistants

#1245 Hide upload button when tools are not available
  src/lib/components/chat/ChatWindow.svelte
Labels: bug, front

#1240 Feat: Delete branch #1210
  src/lib/components/chat/ChatMessage.svelte
  src/routes/conversation/[id]/+page.server.ts
Labels: enhancement, front, back

#1248 Handle errors gracefully in building PlaywrightBlocker
  src/lib/server/websearch/scrape/playwright.ts
Labels: bug, websearch

#1249 Bump version to `0.9.1`
  package-lock.json
  package.json
Labels: CI/CD

#1251 Fix max upload size in huggingchat
  src/lib/utils/messageUpdates.ts
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, front, back

#1256 Add createdAt filter on messageEvents
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, back

#1272 Reduce context window on zephyr orpo
  chart/env/prod.yaml
Labels: models, huggingchat

#1279 Add SD3 as a tool
  src/lib/server/tools/images/generation.ts
Labels: enhancement, tools, huggingchat

#1281 chore(deps): update major versions on svelte, sveltekit & node
  package-lock.json
  package.json
  src/lib/components/ExpandNavigation.svelte
  src/lib/components/MobileNav.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/Pagination.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/server/endpoints/anthropic/utils.ts
  src/lib/server/endpoints/cohere/endpointCohere.ts
  src/routes/+layout.svelte
  src/routes/assistants/+page.svelte
  src/routes/settings/(nav)/+page.svelte
  svelte.config.js
Labels: dependencies

#1280 fix: increase body size limit in docker image
  .env
  Dockerfile
Labels: bug, back

#1292 Request less `max_new_tokens` on tools and reduce `truncate` on CMD R+
  chart/env/prod.yaml
  src/lib/server/textGeneration/tools.ts
Labels: huggingchat

#1296 Fix `updateLocalEnv` to go with the new secrets config
  scripts/updateLocalEnv.ts
Labels: bug, CI/CD, huggingchat

#1305 Standardize llama.cpp endpoint with `baseURL`
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
Labels: bug, back

#1313 Model update 27-06-24
  chart/env/prod.yaml
Labels: models, huggingchat
