Repository huggingface/chat-ui, pull requests merged in 2024-03, with the labels that each got.

#891 Make sure we properly close the stream when done
  src/routes/conversation/[id]/+page.svelte
Labels: bug, front

#892 Improve error handling when posting new messages
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, front, back

#898 Fix issue with "continue" feature on llama.cpp endpoints
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
Labels: bug, models

#841 [Assistants] Filter on names
  src/lib/server/database.ts
  src/lib/types/Assistant.ts
  src/lib/utils/debounce.ts
  src/lib/utils/searchTokens.ts
  src/routes/assistants/+page.server.ts
  src/routes/assistants/+page.svelte
  src/routes/settings/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/assistants/new/+page.server.ts
Labels: enhancement, front, back, assistants

#897 Automated migration setup
  src/hooks.server.ts
  src/lib/migrations/lock.ts
  src/lib/migrations/migrations.spec.ts
  src/lib/migrations/migrations.ts
  src/lib/migrations/routines/01-update-search-assistants.ts
  src/lib/migrations/routines/index.ts
  src/lib/server/database.ts
  src/lib/types/MigrationResult.ts
  src/lib/types/Semaphore.ts
Labels: enhancement, back

#912 Include last chunk in websearch context
  src/lib/server/sentenceSimilarity.ts
Labels: bug, websearch

#900 Make assistant settings form fill the modal
  src/lib/components/AssistantSettings.svelte
  src/routes/settings/(nav)/+layout.svelte
  src/routes/settings/(nav)/+page.svelte
  src/routes/settings/(nav)/+server.ts
  src/routes/settings/(nav)/[...model]/+page.svelte
  src/routes/settings/(nav)/[...model]/+page.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/+page.ts
  src/routes/settings/(nav)/assistants/[assistantId]/ReportModal.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/avatar.jpg/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page@settings.svelte
  src/routes/settings/(nav)/assistants/new/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page@settings.svelte
  src/routes/settings/+layout.svelte
Labels: front, assistants

#858 Direct model page
  src/routes/models/+page.svelte
  src/routes/models/[...model]/+page.server.ts
  src/routes/models/[...model]/+page.svelte
  src/routes/models/[...model]/thumbnail.png/+server.ts
  src/routes/models/[...model]/thumbnail.png/ModelThumbnail.svelte
  src/routes/settings/(nav)/[...model]/+page.svelte
Labels: enhancement, front, back

#918 Remove double meta tags on models page
  src/routes/+layout.svelte
  src/routes/models/[...model]/+page.svelte
  src/routes/models/[...model]/thumbnail.png/ModelThumbnail.svelte
Labels: bug, front

#812 Add websearch controls for assistants
  .env
  .env.template
  package-lock.json
  package.json
  src/lib/components/AssistantSettings.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/icons/IconInternet.svelte
  src/lib/server/isURLLocal.spec.ts
  src/lib/server/isURLLocal.ts
  src/lib/server/websearch/generateQuery.ts
  src/lib/server/websearch/parseWeb.ts
  src/lib/server/websearch/runWebSearch.ts
  src/lib/types/Assistant.ts
  src/lib/utils/parseStringToList.ts
  src/routes/+layout.server.ts
  src/routes/assistants/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/+layout.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
Labels: enhancement, front, back, websearch, assistants

#931 Remove extra > in URLs
  src/lib/components/chat/ChatMessage.svelte
Labels: bug, front

#929 Fix multi domains for assistants
  src/lib/server/websearch/runWebSearch.ts
Labels: websearch, assistants

#820 Fix model identification when creating conversations
  src/routes/conversation/+server.ts
Labels: bug, back

#793 Update public disclaimer: personal data
  .env
Labels: huggingchat

#936 feat: smooth and combine token output
  src/lib/utils/messageUpdates.ts
  src/routes/conversation/[id]/+page.svelte
Labels: enhancement, front

#850 Count system prompt tokens
  .env.template
  src/lib/components/AssistantSettings.svelte
  src/lib/components/TokensCounter.svelte
  src/lib/server/models.ts
  src/lib/types/Model.ts
  src/routes/+layout.server.ts
  src/routes/api/models/+server.ts
  src/routes/settings/(nav)/[...model]/+page.svelte
Labels: enhancement, front, back

#949 Dynamic system instructions
  src/lib/components/AssistantSettings.svelte
  src/lib/components/TokensCounter.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/types/Assistant.ts
  src/routes/assistants/+page.svelte
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
  src/routes/settings/+layout.svelte
Labels: websearch, assistants

#959 Expose sampling controls in assistants (#955)
  src/lib/components/AssistantSettings.svelte
  src/lib/components/HoverTooltip.svelte
  src/lib/server/endpoints/anthropic/endpointAnthropic.ts
  src/lib/server/endpoints/aws/endpointAws.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/endpoints/ollama/endpointOllama.ts
  src/lib/server/endpoints/openai/endpointOai.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/types/Assistant.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
Labels: enhancement, assistants

#957 Remove commented out code in tailwind config
  tailwind.config.cjs
Labels: bug, front

#938 [Assistants] trending feature
  src/hooks.server.ts
  src/lib/assistantStats/refresh-assistants-counts.ts
  src/lib/migrations/lock.ts
  src/lib/migrations/migrations.spec.ts
  src/lib/migrations/migrations.ts
  src/lib/server/database.ts
  src/lib/types/Assistant.ts
  src/lib/types/AssistantStats.ts
  src/routes/assistants/+page.server.ts
  src/routes/assistants/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
Labels: assistants
