Repository huggingface/chat-ui, pull requests merged in 2024-08, with the labels that each got.

#1382 fix(cohere): pass toolResults only when needed to cohere endpoint type
  src/lib/server/endpoints/cohere/endpointCohere.ts
Labels: bug, models

#1389 fix(assistant): add correct steps to repetition penalty
  src/lib/components/AssistantSettings.svelte
Labels: front

#1328 add android id in the hf manifest
  src/routes/+layout.svelte
  static/huggingchat/icon-144x144.png
  static/huggingchat/icon-192x192.png
  static/huggingchat/icon-36x36.png
  static/huggingchat/icon-48x48.png
  static/huggingchat/icon-72x72.png
  static/huggingchat/icon-96x96.png
  static/huggingchat/manifest.json
Labels: enhancement, front, huggingchat

#1390 feat(android): disable tools on android app
  src/routes/+layout.server.ts
  src/routes/conversation/[id]/+server.ts
Labels: front, back

#1395 Major bump to sveltekit & node-adapter versions
  package-lock.json
  package.json
  src/hooks.server.ts
  src/lib/components/ExpandNavigation.svelte
  src/lib/components/MobileNav.svelte
  src/lib/components/NavConversationItem.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/Pagination.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/server/auth.ts
  src/lib/server/endpoints/anthropic/utils.ts
  src/lib/server/endpoints/cohere/endpointCohere.ts
  src/lib/server/exitHandler.ts
  src/lib/server/files/downloadFile.ts
  src/routes/+layout.svelte
  src/routes/admin/export/+server.ts
  src/routes/assistant/[assistantId]/+page.server.ts
  src/routes/assistant/[assistantId]/thumbnail.png/+server.ts
  src/routes/assistants/+page.server.ts
  src/routes/assistants/+page.svelte
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.server.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts
  src/routes/conversation/[id]/message/[messageId]/vote/+server.ts
  src/routes/conversation/[id]/output/[sha256]/+server.ts
  src/routes/conversation/[id]/share/+server.ts
  src/routes/conversation/[id]/stop-generating/+server.ts
  src/routes/conversations/+page.server.ts
  src/routes/login/+page.server.ts
  src/routes/login/callback/+page.server.ts
  src/routes/login/callback/updateUser.ts
  src/routes/logout/+page.server.ts
  src/routes/models/[...model]/+page.server.ts
  src/routes/models/[...model]/thumbnail.png/+server.ts
  src/routes/r/[id]/+page.ts
  src/routes/settings/(nav)/+page.svelte
  src/routes/settings/(nav)/[...model]/+page.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.ts
  src/routes/settings/(nav)/assistants/[assistantId]/avatar.jpg/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
  svelte.config.js
Labels: enhancement, dependencies

#1405 fix(featureflags): use correct env vars
  chart/env/prod.yaml
  src/routes/login/callback/updateUser.ts
Labels: bug, back

#1408 feat(media): support audio & video files
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/UploadedFile.svelte
  src/lib/components/players/AudioPlayer.svelte
Labels: enhancement, front

#1411 feat(tools): use gradio ETA for tools
  src/lib/components/chat/ToolUpdate.svelte
  src/lib/server/textGeneration/tools.ts
  src/lib/server/tools/index.ts
  src/lib/server/tools/utils.ts
  src/lib/types/MessageUpdate.ts
  src/lib/types/Tool.ts
Labels: front, back, tools

#1414 chores(deps): update Transformers to latest version and remove chat templates for all models
  chart/env/prod.yaml
  package-lock.json
  package.json
  src/lib/components/TokensCounter.svelte
  src/lib/server/embeddingEndpoints/transformersjs/embeddingEndpoints.ts
  src/lib/server/models.ts
  src/lib/server/sentenceSimilarity.ts
  src/lib/utils/getTokenizer.ts
  vite.config.ts
Labels: dependencies

#1422 build(config): remove 405B from prod config
  chart/env/prod.yaml
Labels: huggingchat

#1421 feat(assistants): use community tools in assistants
  src/lib/components/AssistantSettings.svelte
  src/lib/components/AssistantToolPicker.svelte
  src/lib/components/ToolBadge.svelte
  src/lib/components/ToolLogo.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/server/models.ts
  src/lib/server/textGeneration/assistant.ts
  src/lib/server/textGeneration/index.ts
  src/lib/server/textGeneration/tools.ts
  src/lib/server/textGeneration/types.ts
  src/lib/types/Assistant.ts
  src/routes/api/tools/[toolId]/+server.ts
  src/routes/api/tools/search/+server.ts
  src/routes/assistants/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page@settings.svelte
  src/routes/settings/(nav)/assistants/new/+page.server.ts
Labels: enhancement, front, back, tools, assistants

#1420 Websearch using Bing API
  .env
  src/lib/server/websearch/search/endpoints.ts
  src/lib/server/websearch/search/endpoints/bing.ts
  src/lib/types/WebSearch.ts
  src/routes/+layout.server.ts
Labels: websearch

#1430 fix(config): test setup update
  package.json
  scripts/setupTest.ts
  tsconfig.json
  vite.config.ts
Labels: bug, back

#1427 Configurable websearch timeout
  .env
  src/lib/server/websearch/scrape/playwright.ts
Labels: websearch

#1419 Dynamic credential resolution for AWS endpoints
  package-lock.json
  package.json
  src/lib/server/endpoints/aws/endpointAws.ts
Labels: models

#1216 Let users access the API using their HF token
  .env
  src/hooks.server.ts
  src/lib/server/database.ts
  src/lib/types/TokenCache.ts
Labels: back, api

#1435 feat(tools): specify either space namespace or huggingface.co URL
  src/lib/server/tools/index.ts
  src/lib/utils/getGradioApi.ts
  src/routes/api/spaces-config/+server.ts
Labels: tools

#1413 Add support for Anthropic models via AWS Bedrock
  package-lock.json
  package.json
  src/lib/server/endpoints/aws/endpointBedrock.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/models.ts
Labels: models

#1437 feat(assistants): better distinction between my own assistants and other people's assistants
  src/routes/settings/(nav)/+layout.svelte
Labels: front, assistants
