Repository huggingface/chat-ui, pull requests merged in 2024-04, with the labels that each got.

#965 Add share button for assistant intro page (#960)
  src/lib/components/chat/AssistantIntroduction.svelte
Labels: front, assistants

#962 Fix button placement on assistant edit/create form
  src/lib/components/AssistantSettings.svelte
Labels: bug, front

#964 Group tokens randomly
  src/routes/conversation/[id]/+server.ts
Labels: back

#972 Implement Cloudflare Workers AI endpoint (#907)
  .env
  README.md
  src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/models.ts
Labels: models

#744 Use jinja template for chat formatting (#730)
  .env.template
  package-lock.json
  package.json
  src/lib/components/TokensCounter.svelte
  src/lib/server/embeddingEndpoints/transformersjs/embeddingEndpoints.ts
  src/lib/server/models.ts
  src/lib/types/Template.ts
  src/lib/utils/getTokenizer.ts
  src/lib/utils/template.ts
Labels: documentation, enhancement, back

#976 Add support for cohere endpoints
  .env
  README.md
  package-lock.json
  package.json
  src/lib/server/endpoints/cohere/endpointCohere.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/models.ts
Labels: enhancement, models

#985 Set ChatML as default chat prompt template
  src/lib/server/models.ts
Labels: bug, back

#987 Move default template so it doesn't override tokenizer
  src/lib/server/models.ts
Labels: bug, back

#988 Publish docker images based on package.json version
  .github/workflows/build-image.yml
Labels: enhancement, CI/CD

#989 Make sure CI/CD is the same for no DB image
  .github/workflows/build-image.yml
Labels: bug, CI/CD

#990 Use raw for versioning
  .github/workflows/build-image.yml
Labels: bug, CI/CD

#992 Bump version to 0.8.1
  package-lock.json
  package.json
Labels: CI/CD

#993 Deploy HuggingChat changes manually only
  .github/workflows/deploy-release.yml
Labels: CI/CD, huggingchat

#995 Add gemma 7B it to old models
  .env.template
Labels: models, huggingchat

#998 Update models and add check for assistants model on startup
  .env.template
  src/lib/components/AssistantSettings.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/migrations/migrations.spec.ts
  src/lib/migrations/migrations.ts
  src/lib/migrations/routines/02-update-assistants-models.ts
  src/lib/migrations/routines/index.ts
Labels: huggingchat, assistants

#1001 Add Command R+ to HuggingChat config
  .env.template
Labels: models, huggingchat

#1006 Show the assistant model name in the chat input
  src/lib/components/chat/ChatWindow.svelte
Labels: bug, front

#1007 Send characters by groups of 5
  src/routes/conversation/[id]/+server.ts
Labels: back

#1008 Add new model to HuggingChat config
  .env.template
Labels: models, huggingchat

#1019 Remove GA from HuggingChat config
  .env.template
Labels: huggingchat

#1023 Add assistant instructions to first system message
  src/routes/conversation/+server.ts
Labels: bug, back, assistants

#1026 Add instructions for running a copy of HuggingChat
  README.md
Labels: documentation

#1030 Add logs to tokenizer fetch
  src/lib/server/models.ts
Labels: bug

#1037 Use inference API for embeddings in huggingchat prod
  .env.template
  src/lib/server/embeddingEndpoints/embeddingEndpoints.ts
  src/lib/server/embeddingEndpoints/hfApi/embeddingHfApi.ts
  src/lib/server/embeddingEndpoints/tei/embeddingEndpoints.ts
  src/lib/server/embeddingModels.ts
Labels: websearch, huggingchat

#1038 return empty if error on hfapi endpoint
  src/lib/server/embeddingEndpoints/hfApi/embeddingHfApi.ts
Labels: back

#1044 Kill app on tokenizer load fail
  src/lib/server/models.ts
Labels: bug, back, huggingchat

#1045 Use `user` in docker image for spaces
  Dockerfile
Labels: docker

#1046 Docker chown change
  Dockerfile
Labels: docker

#1047 Dispose of embeddings pipeline occasionally to clear memory
  src/lib/server/embeddingEndpoints/transformersjs/embeddingEndpoints.ts
Labels: websearch

#1048 Always dispose of pipeline for embeddings after use
  src/lib/server/embeddingEndpoints/transformersjs/embeddingEndpoints.ts
Labels: websearch, huggingchat

#1049 Use dedicated endpoint for embeddings
  .env.template
Labels: huggingchat

#1051 Use TEI space in prod
  .env.template
  src/lib/server/embeddingEndpoints/tei/embeddingEndpoints.ts
Labels: huggingchat

#1053 fix: See all your assistants regardless of usercount
  src/routes/api/assistants/+server.ts
  src/routes/assistants/+page.server.ts
Labels: bug, back, assistants

#1054 Only require featured assistants for other users' assistants
  src/routes/api/assistants/+server.ts
  src/routes/assistants/+page.server.ts
Labels: bug, back, assistants

#1058 Add Phi 3 to huggingchat
  .env.template
Labels: models, huggingchat

#1059 Add extra stop tokens for phi 3
  .env.template
Labels: models, huggingchat

#1071 Add phi chat prompt template
  .env.template
Labels: huggingchat

#1076 Add `ALLOW_INSECURE_COOKIES` feature flag
  .env
  README.md
  src/lib/server/auth.ts
  src/routes/logout/+page.server.ts
Labels: enhancement, back

#1070 🎨 Add color for copy icon
  src/lib/components/CopyToClipBoardBtn.svelte
Labels: bug, front

#1078 set `sameSite` to `lax` when allowing insecure cookies
  src/lib/server/auth.ts
  src/routes/logout/+page.server.ts
Labels: bug, back

#1081 Adds <s> to Phi-3-mini-4k-instruct template configuration
  .env.template
Labels: huggingchat

#1086 Use pino for logs
  package-lock.json
  package.json
  src/app.d.ts
  src/hooks.server.ts
  src/lib/assistantStats/refresh-assistants-counts.ts
  src/lib/migrations/migrations.ts
  src/lib/server/abortedGenerations.ts
  src/lib/server/auth.ts
  src/lib/server/database.ts
  src/lib/server/embeddingEndpoints/hfApi/embeddingHfApi.ts
  src/lib/server/embeddingEndpoints/tei/embeddingEndpoints.ts
  src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
  src/lib/server/endpoints/langserve/endpointLangserve.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/logger.ts
  src/lib/server/models.ts
  src/lib/server/preprocessMessages.ts
  src/lib/server/summarize.ts
  src/lib/server/websearch/searchSearxng.ts
  src/routes/+error.svelte
  src/routes/admin/export/+server.ts
  src/routes/admin/stats/compute/+server.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
Labels: enhancement, back

#1089 Add the simplest healthcheck route
  src/routes/healthcheck/+server.ts
Labels: enhancement, back

#1090 Add truncate to task model
  .env.template
Labels: models, huggingchat
