Repository huggingface/chat-ui, pull requests merged in 2024-05, with the labels that each got.

#1099 Use correct internal registry
  .github/workflows/deploy-prod.yml
Labels: CI/CD

#1100 Clean up internal image action
  .github/workflows/deploy-prod.yml
Labels: CI/CD

#1105 fix(chart): add ADDRESS_HEADER and XFF_DEPTH for IP rate limiting
  chart/env/prod.yaml
Labels: CI/CD

#1065 [VertexAI] Add support for tools parameter
  README.md
  src/lib/server/endpoints/google/endpointVertex.ts
Labels: enhancement, back, models

#1108 Bump version to 0.8.4
  package-lock.json
  package.json
Labels: CI/CD

#1107 Update scripts & documentations to reflect new prod setup
  .env.template
  .github/workflows/deploy-release.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/updateLocalEnv.ts
  scripts/updateProdEnv.ts
Labels: documentation, CI/CD

#1077 Fix OpenAI Embeddings Auth Issue
  src/lib/server/embeddingEndpoints/openai/embeddingEndpoints.ts
Labels: enhancement, models

#1095 Ensures more consistent hyperparameters to Phi-3-mini-4k-instruct
  chart/env/prod.yaml
Labels: models, huggingchat

#1119 Add temperature to Llama 3 70B on HuggingChat
  chart/env/prod.yaml
Labels: huggingchat

#958 feat: add support for anthropic on vertex
  README.md
  package-lock.json
  package.json
  src/lib/server/endpoints/anthropic/endpointAnthropicVertex.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/models.ts
Labels: enhancement, models

#1122 Remove trim on user input
  src/routes/conversation/[id]/+server.ts
Labels: bug, back

#1130 Make messages before login a aws param
  chart/env/prod.yaml
Labels: huggingchat

#1172 Ony call tools if model.tools is true
  src/lib/server/textGeneration/index.ts
Labels: bug, back

#1173 fix streaming not updating on front-end
  src/routes/conversation/[id]/+page.svelte
Labels: bug, front

#1177 Fix reduced motion mode causing 500 on ssr
  src/lib/components/chat/ChatMessage.svelte
Labels: bug, front

#1141 Update documentation of OpenAI compatible server configuration
  README.md
Labels: documentation, models

#1144 Improve helm chart
  chart/templates/deployment.yaml
  chart/templates/ingress.yaml
  chart/values.yaml
Labels: CI/CD

#1162 fix: parse ISS if returned in OIDC flow
  src/lib/server/auth.ts
  src/routes/login/callback/+page.server.ts
Labels: bug, back

#1155 Hosted Documentation
  .github/workflows/build-docs.yml
  .github/workflows/build-pr-docs.yml
  .github/workflows/upload-pr-documentation.yml
  README.md
  docs/source/_toctree.yml
  docs/source/configuration/common-issues.md
  docs/source/configuration/embeddings.md
  docs/source/configuration/models/multimodal.md
  docs/source/configuration/models/overview.md
  docs/source/configuration/models/providers/anthropic.md
  docs/source/configuration/models/providers/aws.md
  docs/source/configuration/models/providers/cloudflare.md
  docs/source/configuration/models/providers/cohere.md
  docs/source/configuration/models/providers/google.md
  docs/source/configuration/models/providers/langserve.md
  docs/source/configuration/models/providers/llamacpp.md
  docs/source/configuration/models/providers/ollama.md
  docs/source/configuration/models/providers/openai.md
  docs/source/configuration/models/providers/tgi.md
  docs/source/configuration/models/tools.md
  docs/source/configuration/open-id.md
  docs/source/configuration/overview.md
  docs/source/configuration/theming.md
  docs/source/configuration/web-search.md
  docs/source/developing/architecture.md
  docs/source/developing/copy-huggingchat.md
  docs/source/index.md
  docs/source/installation/docker.md
  docs/source/installation/helm.md
  docs/source/installation/local.md
  docs/source/installation/spaces.md
Labels: documentation, enhancement

#1186 Add metrics for models, tools, websearch
  src/lib/server/metrics.ts
  src/lib/server/textGeneration/tools.ts
  src/lib/server/websearch/embed/embed.ts
  src/lib/server/websearch/runWebSearch.ts
  src/lib/server/websearch/scrape/scrape.ts
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, observability

#1179 Reduce message update size returned by websearch
  src/lib/migrations/routines/04-update-message-updates.ts
  src/lib/migrations/routines/06-trim-message-updates.ts
  src/lib/migrations/routines/index.ts
  src/lib/server/websearch/runWebSearch.ts
  src/lib/server/websearch/update.ts
  src/lib/types/MessageUpdate.ts
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, websearch

#1168 Simplify tool error handling
  src/lib/server/textGeneration/tools.ts
  src/lib/server/tools/calculator.ts
  src/lib/server/tools/directlyAnswer.ts
  src/lib/server/tools/documentParser.ts
  src/lib/server/tools/images/editing.ts
  src/lib/server/tools/images/generation.ts
  src/lib/server/tools/index.ts
  src/lib/server/tools/web/search.ts
  src/lib/server/tools/web/url.ts
  src/lib/utils/stringifyError.ts
Labels: enhancement, tools

#1188 Add a loading bar for tools
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ToolUpdate.svelte
  src/lib/types/Tool.ts
  src/routes/+layout.server.ts
Labels: enhancement, front, back, tools

#1197 Fix display websearch when using tools
  src/lib/components/chat/ToolUpdate.svelte
Labels: bug, front

#1199 Bump version to 0.9.0
  package-lock.json
  package.json
Labels: CI/CD

#1209 fix: fix installation documentation overview links
  docs/source/installation/docker.md
  docs/source/installation/local.md
Labels: documentation

#1213 Add super basic admin feature
  src/lib/types/User.ts
  src/routes/+layout.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.svelte
Labels: enhancement, front, back, assistants

#1215 Fix migration object id
  src/lib/migrations/routines/06-trim-message-updates.ts
Labels: migrations

#1196 Add support for SearchApi API
  .env
  README.md
  docs/source/configuration/web-search.md
  src/lib/server/websearch/search/endpoints.ts
  src/lib/server/websearch/search/endpoints/searchApi.ts
  src/routes/+layout.server.ts
Labels: enhancement, websearch

#1206 feat: support file pasting in chat input
  src/lib/components/chat/ChatInput.svelte
  src/lib/components/chat/ChatWindow.svelte
Labels: tools

#1205 feat: skip tools when all disabled
  src/lib/server/textGeneration/index.ts
Labels: tools

#1222 Only paste or drop the allowed MIME types
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/chat/FileDropzone.svelte
Labels: front, tools

#1204 feat: mime types on tools, show upload btn on demand
  src/lib/components/ToolsMenu.svelte
  src/lib/components/UploadBtn.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/chat/FileDropzone.svelte
  src/lib/server/tools/documentParser.ts
  src/lib/server/tools/images/editing.ts
  src/lib/types/Tool.ts
  src/routes/+layout.server.ts
Labels: tools

#1227 Send `ollama pull` request if model is not available locally
  src/lib/server/endpoints/ollama/endpointOllama.ts
Labels: enhancement, back, models

#1233 Add sampling parameter support to cloudflare
  src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
Labels: enhancement, models
