Repository huggingface/chat-ui, pull requests merged in 2024-02, with the labels that each got.

#740 Top assistants page
  src/lib/components/AssistantSettings.svelte
  src/lib/components/NavConversationItem.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/server/database.ts
  src/lib/types/Assistant.ts
  src/lib/utils/isHuggingChat.ts
  src/routes/assistant/[assistantId]/+page.svelte
  src/routes/assistants/+page.server.ts
  src/routes/assistants/+page.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/+page.svelte
  src/routes/settings/assistants/[assistantId]/+page.server.ts
  src/routes/settings/assistants/[assistantId]/+page.svelte
  src/routes/settings/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/assistants/new/+page.server.ts
Labels: enhancement, front, back

#759 Hide websearch on assistants
  src/routes/conversation/[id]/+page.svelte
Labels: bug, front

#763 add an api endpoint to get current user's informations
  src/routes/api/user/+server.ts
Labels: enhancement, back

#765 Bring back featured check on top assistants page
  src/lib/server/database.ts
  src/lib/types/Assistant.ts
  src/routes/assistants/+page.server.ts
  src/routes/settings/assistants/new/+page.server.ts
Labels: enhancement, front, back

#762 Convert all assistants avatar to jpeg server-side
  src/lib/components/AssistantSettings.svelte
  src/lib/components/NavConversationItem.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/components/chat/ChatMessages.svelte
  src/routes/assistant/[assistantId]/+page.svelte
  src/routes/assistants/+page.svelte
  src/routes/settings/+layout.svelte
  src/routes/settings/assistants/[assistantId]/+page.svelte
  src/routes/settings/assistants/[assistantId]/avatar.jpg/+server.ts
  src/routes/settings/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/assistants/new/+page.server.ts
Labels: enhancement, back

#756 Make assistant feature visible globally
  src/lib/components/NavMenu.svelte
  src/routes/settings/+layout.svelte
Labels: front

#776 Use assistant avatar in conversation, if available
  src/lib/components/chat/ChatMessage.svelte
Labels: enhancement, front

#778 Disable websearch on assistants, server & client side
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: bug, back

#779 Add Plausible analytics
  .env
  .env.template
  src/routes/+layout.svelte
Labels: enhancement, back

#760 Several QoL contributions
  .env
  .env.template
  README.md
  src/lib/components/DisclaimerModal.svelte
  src/lib/server/endpoints/openai/endpointOai.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/[...model]/+page.svelte
Labels: enhancement, front, back

#790 [Chat input] Blur on submit
  src/lib/components/chat/ChatInput.svelte
Labels: bug, front

#803 fix continue button on openai endpoint
  src/lib/server/endpoints/openai/openAIChatToTextGenerationStream.ts
  src/lib/server/endpoints/openai/openAICompletionToTextGenerationStream.ts
Labels: bug, back, models

#806 Fix delete assistant query performance
  src/lib/server/database.ts
  src/routes/settings/assistants/[assistantId]/+page.server.ts
Labels: bug, back, assistants

#785 [fix] If APP_BASE is empty, go to '/' instead of an empty string.
  src/routes/assistant/[assistantId]/+page.svelte
Labels: bug, back

#814 Only use plausible if PUBLIC_ORIGIN is set
  src/routes/+layout.svelte
Labels: bug, back

#755 Make lorax openai endpoint working
  src/lib/server/models.ts
Labels: models

#825 Ask for a reason when reporting assistants
  src/lib/components/Modal.svelte
  src/lib/types/Report.ts
  src/routes/settings/assistants/[assistantId]/+page.server.ts
  src/routes/settings/assistants/[assistantId]/+page.svelte
  src/routes/settings/assistants/[assistantId]/ReportModal.svelte
Labels: enhancement, assistants

#807 Conversation trees (#223)
  .env.template
  src/lib/buildPrompt.ts
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatMessages.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/server/database.ts
  src/lib/server/endpoints/aws/endpointAws.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/llamacpp/endpointLlamacpp.ts
  src/lib/server/endpoints/ollama/endpointOllama.ts
  src/lib/server/endpoints/openai/endpointOai.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/server/generateFromDefaultEndpoint.ts
  src/lib/server/preprocessMessages.ts
  src/lib/server/websearch/runWebSearch.ts
  src/lib/stores/convTree.ts
  src/lib/types/Conversation.ts
  src/lib/types/Message.ts
  src/lib/types/SharedConversation.ts
  src/lib/utils/tree/addChildren.spec.ts
  src/lib/utils/tree/addChildren.ts
  src/lib/utils/tree/addSibling.spec.ts
  src/lib/utils/tree/addSibling.ts
  src/lib/utils/tree/buildSubtree.spec.ts
  src/lib/utils/tree/buildSubtree.ts
  src/lib/utils/tree/convertLegacyConversation.spec.ts
  src/lib/utils/tree/convertLegacyConversation.ts
  src/lib/utils/tree/isMessageId.spec.ts
  src/lib/utils/tree/isMessageId.ts
  src/lib/utils/tree/treeHelpers.spec.ts
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.server.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
  src/routes/conversation/[id]/message/[messageId]/prompt/+server.ts
  src/routes/conversation/[id]/share/+server.ts
Labels: enhancement, front, back

#848 Bring back model urls
  .env.template
Labels: huggingchat

#856 hotfix websiteUrl gemma
  .env.template
Labels: models

#857 Update gemma description
  .env.template
Labels: models

#839 Allow retry on shared conversations
  src/lib/components/chat/ChatMessage.svelte
Labels: bug, front

#863 [Mongo] count messages (aggregate) only when needed
  src/routes/+layout.server.ts
Labels: enhancement, back

#859 [Mongo] optimizations
  src/routes/+layout.server.ts
  src/routes/settings/+layout.server.ts
Labels: enhancement, back

#872 Small UX updates assistants
  src/lib/stores/settings.ts
  src/routes/+layout.svelte
  src/routes/assistant/[assistantId]/+page.svelte
  src/routes/assistants/+page.svelte
Labels: enhancement, front

#876 Pass websearch to `preprocessMessages`
  src/lib/server/preprocessMessages.ts
  src/routes/conversation/[id]/+server.ts
Labels: bug, websearch

#882 Use `uuid` for message ID generation instead of crypto method
  package-lock.json
  package.json
  src/lib/types/Message.ts
  src/lib/utils/tree/addChildren.ts
  src/lib/utils/tree/addSibling.ts
  src/lib/utils/tree/convertLegacyConversation.ts
  src/lib/utils/tree/isMessageId.spec.ts
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.svelte
  vite.config.ts
Labels: bug

#884 Fix Error: Ancestor Not Found issue
  src/routes/conversation/[id]/+page.svelte
Labels: bug, front

#880 Add a simple populate script
  README.md
  package-lock.json
  package.json
  scripts/populate.ts
Labels: enhancement, back, dependencies
