Repository huggingface/chat-ui, pull requests merged in 2024-07, with the labels that each got.

#1304 Add CSP protection on uploaded files
  src/routes/conversation/[id]/output/[sha256]/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/avatar.jpg/+server.ts
Labels: back

#1201 feat: allow disabling metrics server, consolidate exit handlers
  .env
  chart/env/prod.yaml
  docs/source/_toctree.yml
  docs/source/configuration/metrics.md
  src/hooks.server.ts
  src/lib/server/abortedGenerations.ts
  src/lib/server/database.ts
  src/lib/server/exitHandler.ts
  src/lib/server/metrics.ts
  src/lib/server/websearch/scrape/playwright.ts
Labels: back

#1297 Community tools
  chart/env/prod.yaml
  scripts/populate.ts
  src/lib/buildPrompt.ts
  src/lib/components/NavMenu.svelte
  src/lib/components/ToolLogo.svelte
  src/lib/components/ToolsMenu.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/chat/ToolUpdate.svelte
  src/lib/migrations/routines/03-add-tools-in-settings.ts
  src/lib/server/database.ts
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/metrics.ts
  src/lib/server/models.ts
  src/lib/server/textGeneration/tools.ts
  src/lib/server/textGeneration/types.ts
  src/lib/server/tools/calculator.ts
  src/lib/server/tools/directlyAnswer.ts
  src/lib/server/tools/index.ts
  src/lib/server/tools/web/search.ts
  src/lib/server/tools/web/url.ts
  src/lib/server/usageLimits.ts
  src/lib/stores/settings.ts
  src/lib/types/Report.ts
  src/lib/types/Settings.ts
  src/lib/types/Template.ts
  src/lib/types/Tool.ts
  src/lib/utils/messageUpdates.ts
  src/lib/utils/tools.ts
  src/routes/+layout.server.ts
  src/routes/assistants/+page.server.ts
  src/routes/conversation/[id]/+server.ts
  src/routes/settings/(nav)/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/+page.server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/ReportModal.svelte
  src/routes/settings/+layout.server.ts
  src/routes/tools/+layout.svelte
  src/routes/tools/+page.server.ts
  src/routes/tools/+page.svelte
  src/routes/tools/ToolEdit.svelte
  src/routes/tools/[toolId]/+layout.server.ts
  src/routes/tools/[toolId]/+page.server.ts
  src/routes/tools/[toolId]/+page.svelte
  src/routes/tools/[toolId]/edit/+page.server.ts
  src/routes/tools/[toolId]/edit/+page.svelte
  src/routes/tools/new/+page.server.ts
  src/routes/tools/new/+page.svelte
  vite.config.ts
Labels: front, back, tools

#1319 Remove Gemma 2 from HuggingChat
  chart/env/prod.yaml
Labels: huggingchat

#1324 Move stats to their own job
  src/hooks.server.ts
  src/lib/jobs/refresh-assistants-counts.ts
  src/lib/jobs/refresh-conversation-stats.ts
  src/routes/admin/stats/compute/+server.ts
Labels: back

#1320 Added husky for pre committing.
  .husky/lint-stage-config.js
  .husky/pre-commit
  Dockerfile
  package-lock.json
  package.json
Labels: enhancement, CI/CD

#1330 Add Google Gemini API Support
  docs/source/configuration/models/providers/google.md
  package-lock.json
  package.json
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/google/endpointGenAI.ts
  src/lib/server/models.ts
Labels: enhancement, back, models

#1347 feat(upload): Enable multi-file in dropzone
  src/lib/components/chat/FileDropzone.svelte
Labels: enhancement, front

#1355 feat(models): Llama 3.1 support
  chart/env/prod.yaml
  src/lib/components/ModelCardMetadata.svelte
  src/lib/migrations/routines/07-reset-tools-in-settings.ts
  src/lib/migrations/routines/index.ts
  src/lib/server/models.ts
  src/lib/server/textGeneration/tools.ts
  src/lib/server/tools/calculator.ts
  src/lib/server/tools/documentParser.ts
  src/lib/server/tools/images/editing.ts
  src/lib/server/tools/images/generation.ts
  src/lib/server/tools/web/search.ts
  src/lib/server/tools/web/url.ts
  src/lib/types/Template.ts
Labels: models, huggingchat

#1360 fix(disclaimer): only show disclaimer if PUBLIC_APP_DISCLAIMER is 1
  src/routes/+layout.svelte
Labels: bug, front

#1365 feat(auth): Add admin & early access flags based on orgs membership
  .env
  chart/env/prod.yaml
  src/lib/types/User.ts
  src/routes/+layout.server.ts
  src/routes/login/callback/updateUser.ts
Labels: enhancement, back

#1358 fix(config): remove preprompt for huggingchat llama 3.1
  chart/env/prod.yaml
Labels: models, huggingchat

#1378 Add support to @cf models with cloudflare.com
  src/lib/server/endpoints/cloudflare/endpointCloudflare.ts
Labels: enhancement, back, models
