Repository huggingface/chat-ui, pull requests merged in 2024-09, with the labels that each got.

#1450 Fix typo
  src/lib/components/AssistantSettings.svelte
Labels: bug, front

#1452 fix(assistants): only enable websearch on assistants with RAG
  src/lib/server/textGeneration/tools.ts
Labels: bug, tools, websearch, assistants

#1338 feat: add support for multimodal in Vertex
  README.md
  src/lib/server/endpoints/google/endpointVertex.ts
Labels: enhancement, back, models

#1459 fix(continue): fix continue feature
  src/lib/buildPrompt.ts
  src/lib/server/models.ts
  src/lib/types/Template.ts
Labels: bug, back, models

#1453 feat(models): add transferTo property on old models
  src/lib/migrations/routines/02-update-assistants-models.ts
  src/lib/server/models.ts
Labels: back, models, migrations

#1454 chores(hchat): update cohere command R+ to latest version
  chart/env/prod.yaml
Labels: huggingchat

#1462 feat(conv): let user switch models on conversations with deprecated models
  src/lib/components/chat/ChatWindow.svelte
  src/lib/components/chat/ModelSwitch.svelte
  src/lib/server/models.ts
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, front, back

#1465 fix(assistants): remove websearch from assistant tool options, add websearch in backend logic
  src/lib/server/textGeneration/tools.ts
  src/routes/api/tools/search/+server.ts
Labels: enhancement, tools, websearch, assistants

#1466 fix(tools): tool call name must be a valid python variable name
  src/lib/server/tools/index.ts
Labels: enhancement, tools

#1468 fix(endpoints): make bedrock import optional
  src/lib/server/endpoints/aws/endpointBedrock.ts
Labels: enhancement, models

#1469 pluralize
  src/routes/tools/+page.svelte
  src/routes/tools/[toolId]/+page.svelte
Labels: bug, front, tools

#1433 feat(tools): remove feature flag for tools and use env variable instead
  .env
  chart/env/prod.yaml
  src/lib/components/NavMenu.svelte
  src/lib/components/ToolsMenu.svelte
  src/routes/+layout.server.ts
  src/routes/api/spaces-config/+server.ts
  src/routes/api/tools/[toolId]/+server.ts
  src/routes/api/tools/search/+server.ts
  src/routes/settings/(nav)/+server.ts
  src/routes/settings/(nav)/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/(nav)/assistants/new/+page.server.ts
  src/routes/tools/+layout.ts
  src/routes/tools/+page.server.ts
  src/routes/tools/new/+page.server.ts
Labels: front, back, tools

#1474 feat(tools): add toggle to see unfeatured tools for admins
  src/routes/tools/+page.server.ts
  src/routes/tools/+page.svelte
Labels: enhancement, front, back, tools

#1481 feat(huggingchat): add Qwen 2.5 72B
  chart/env/prod.yaml
Labels: huggingchat

#1480 fix(websearch): fix `webSearch` flag use for model with tool use
  src/lib/server/textGeneration/index.ts
  src/routes/conversation/[id]/+page.svelte
Labels: bug, websearch

#1483 feat(huggingchat): add default instructions to qwen 2.5
  chart/env/prod.yaml
Labels: huggingchat

#1485 feat(huggingchat): Model update 24/09/2024
  chart/env/prod.yaml
Labels: huggingchat

#1488 feat: add link to API playground for compatible models
  src/lib/components/ModelCardMetadata.svelte
  src/lib/server/models.ts
  src/lib/types/Model.ts
  src/routes/+layout.server.ts
  src/routes/api/models/+server.ts
  src/routes/settings/(nav)/[...model]/+page.svelte
Labels: enhancement, front, back

#1491 fix: multimodal on TGI endpoint type
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/server/textGeneration/generate.ts
Labels: bug, back, models

#1494 feat(huggingchat): model config update 25-09-2024
  chart/env/prod.yaml
Labels: huggingchat

#1497 fix(front): fix clipboard copy on chrome
  src/lib/utils/share.ts
Labels: front
