Repository huggingface/chat-ui, pull requests merged in 2024-01, with the labels that each got.

#671 Use JSON5 for parsing all config vars
  package-lock.json
  package.json
  src/lib/components/chat/ChatIntroduction.svelte
  src/lib/server/auth.ts
  src/lib/server/models.ts
  src/lib/server/websearch/generateQuery.ts
Labels: enhancement, back

#675 Fixes "invalid url" error in websearch
  src/lib/server/websearch/runWebSearch.ts
Labels: bug, websearch

#680 Remove falcon 180B
  .env.template
Labels: models

#682 Apply settings without reloading the page
  src/lib/stores/settings.ts
  src/routes/+layout.server.ts
Labels: bug, front

#683 Add doc section about updating HuggingChat
  README.md
Labels: documentation

#687 Update openchat to 0106
  .env.template
Labels: models

#662 [Assistants] Use textToImage task for avatar generation
  .env
  src/lib/components/AssistantSettings.svelte
  src/lib/utils/generateAvatar.ts
  src/lib/utils/timeout.ts
  src/routes/+layout.server.ts
  src/routes/settings/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/assistants/new/+page.server.ts
Labels: enhancement, front, back

#694 Add an endpoints to expose models and conversations
  .env
  .env.template
  src/hooks.server.ts
  src/routes/api/conversations/+server.ts
  src/routes/api/models/+server.ts
Labels: enhancement, back

#696 Set message id on server side
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: back

#700 Add NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  .env.template
  PROMPTS.md
Labels: models

#702 Bump max new tokens for NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  .env.template
Labels: models

#718 Bring back mistral task model
  .env.template
Labels: models

#707 Continue generation feature
  .env.template
  src/lib/buildPrompt.ts
  src/lib/components/ContinueBtn.svelte
  src/lib/components/chat/ChatMessage.svelte
  src/lib/components/chat/ChatMessages.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/server/endpoints/endpoints.ts
  src/lib/server/endpoints/tgi/endpointTgi.ts
  src/lib/types/Message.ts
  src/routes/conversation/[id]/+page.svelte
  src/routes/conversation/[id]/+server.ts
Labels: enhancement, front, back

#639 Assistants feature
  .env
  .env.template
  .vscode/settings.json
  package-lock.json
  package.json
  src/lib/components/AssistantSettings.svelte
  src/lib/components/DisclaimerModal.svelte
  src/lib/components/LoginModal.svelte
  src/lib/components/NavConversationItem.svelte
  src/lib/components/NavMenu.svelte
  src/lib/components/chat/AssistantIntroduction.svelte
  src/lib/components/chat/ChatMessages.svelte
  src/lib/components/chat/ChatWindow.svelte
  src/lib/server/database.ts
  src/lib/stores/settings.ts
  src/lib/types/Assistant.ts
  src/lib/types/ConvSidebar.ts
  src/lib/types/Conversation.ts
  src/lib/types/Report.ts
  src/lib/types/Settings.ts
  src/lib/types/SharedConversation.ts
  src/lib/utils/timeout.ts
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/assistant/[assistantId]/+page.server.ts
  src/routes/assistant/[assistantId]/+page.svelte
  src/routes/assistant/[assistantId]/thumbnail.png/+server.ts
  src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte
  src/routes/conversation/+server.ts
  src/routes/conversation/[id]/+page.server.ts
  src/routes/conversation/[id]/share/+server.ts
  src/routes/settings/+layout.server.ts
  src/routes/settings/+layout.svelte
  src/routes/settings/+server.ts
  src/routes/settings/[...model]/+page.svelte
  src/routes/settings/assistants/[assistantId]/+page.server.ts
  src/routes/settings/assistants/[assistantId]/+page.svelte
  src/routes/settings/assistants/[assistantId]/+page.ts
  src/routes/settings/assistants/[assistantId]/avatar/+server.ts
  src/routes/settings/assistants/[assistantId]/edit/+page.server.ts
  src/routes/settings/assistants/[assistantId]/edit/+page.svelte
  src/routes/settings/assistants/new/+page.server.ts
  src/routes/settings/assistants/new/+page.svelte
  static/fonts/Inter-Black.ttf
  static/fonts/Inter-Bold.ttf
  static/fonts/Inter-ExtraBold.ttf
  static/fonts/Inter-ExtraLight.ttf
  static/fonts/Inter-Light.ttf
  static/fonts/Inter-Medium.ttf
  static/fonts/Inter-Regular.ttf
  static/fonts/Inter-SemiBold.ttf
  static/fonts/Inter-Thin.ttf
Labels: enhancement, front, back

#732 fix: social thumbnail assistants in prod
  src/ambient.d.ts
  src/routes/assistant/[assistantId]/thumbnail.png/+server.ts
  src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte
  vite.config.ts
Labels: bug, back

#734 Fix social thumbnails: images
  package-lock.json
  package.json
  src/routes/assistant/[assistantId]/thumbnail.png/+server.ts
  src/routes/assistant/[assistantId]/thumbnail.png/ChatThumbnail.svelte
Labels: bug, back

#731 Add failure strategy to README.md
  README.md
Labels: documentation, CI/CD

#728 Update nous prompt
  .env.template
  PROMPTS.md
Labels: models

#752 Add CodeLlama-70b-Instruct-hf
  .env
  .env.template
  PROMPTS.md
  src/routes/conversation/[id]/+server.ts
Labels: models

#754 Remove tabs in websearch prompt
  src/lib/buildPrompt.ts
Labels: bug, websearch
