Repository huggingface/chat-ui, pull requests merged in 2025-01, with the labels that each got.

#1639 feat(websearch): skip pages that dont return success
  src/lib/server/websearch/scrape/scrape.ts
Labels: websearch

#1604 Capture screen like similar to Claude
  src/lib/components/chat/ChatInput.svelte
  src/lib/components/icons/IconScreenshot.svelte
  src/lib/utils/screenshot.ts
Labels: front

#1640 feat: show login modal if login is required for creating assistants & tools
  chart/env/prod.yaml
  src/lib/components/chat/ChatWindow.svelte
  src/lib/stores/loginModal.ts
  src/routes/+layout.svelte
  src/routes/assistants/+page.svelte
  src/routes/tools/+page.svelte
Labels: front

#1564 feat: infinite scrolling list of conversations
  src/lib/components/InfiniteScroll.svelte
  src/lib/components/NavMenu.svelte
  src/lib/constants/pagination.ts
  src/routes/+layout.server.ts
  src/routes/api/conversations/+server.ts
Labels: enhancement, front, back

#1661 feat: add indicator for reasoning models in /models page
  src/routes/+layout.server.ts
  src/routes/models/+page.svelte
Labels: front

#1660 feat: add `deepseek-ai/DeepSeek-R1-Distill-Qwen-32B` to HuggingChat config
  chart/env/prod.yaml
  src/lib/components/chat/ChatMessage.svelte
  src/lib/server/textGeneration/generate.ts
Labels: models, huggingchat

#1666 fix: collapse arrow no longer visible on top of settings modal
  src/routes/+layout.svelte
Labels: bug, front
